package types

type InternalError int

const (
	// 100X General ERROR
	ERR_INVALID_PARAMETER InternalError = 1001 + iota
	ERR_MISSING_PARAMETER
	ERR_NOT_FOUND

	// 200X Kubernetes ERROR
	ERR_INVALID_RESOURCE InternalError = 2001 + iota
	ERR_GENERATE_RESOURCE
	ERR_RESOURCE_ALREADY_EXIST
	ERR_RESOURCE_NOT_FOUND
	ERR_PERMISSION_DENIED
	ERR_RESOURCE_CREATE_FAILED
	ERR_RESOURCE_DELETE_FAILED
	ERR_RESOURCE_UPDATE_FAILED
	ERR_APISERVER_TIMEOUT

	// 300X Authentication and Authorization ERROR
	ERR_INVALID_TOKEN InternalError = 3001 + iota
	ERR_TOKEN_PARSE_FAILED
	ERR_ACCESS_DENIED

	// 400X Configuration ERROR
	ERR_MISSING_CONFIG InternalError = 4001 + iota
	ERR_INVALID_CONFIG

	// 500X Network ERROR
	ERR_REQUEST_TIMEOUT InternalError = 5001 + iota
	ERR_KUBE_CLIENT_CONNECTION_FAILED
	ERR_DNS_RESOLVE_FAILED
)
