// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

import "fmt"

type (
	GPUResource struct {
		Type string `json:"type"`
		Num  string `json:"num"`
	}

	StorageResource struct {
		SystemDisk string        `json:"system_disk"`
		DataVolume []PVCResource `json:"data_volume"`
	}

	PVCResource struct {
		PVC  string `json:"pvc"`
		Size string `json:"size"`
	}

	Resources struct {
		CPU     string      `json:"cpu"`
		Memory  string      `json:"memory"`
		GPU     GPUResource `json:"gpu"`
		GPUType string      `json:"gpu_type"`
	}
)

type CreateInstanceRequest struct {
	RequestUUID     string    `json:"request_uuid"`
	CreateUser      string    `json:"create_user"`
	Name            string    `json:"name"`
	Replicas        int32     `json:"replicas"`
	Image           string    `json:"image"`
	ChargeType      string    `json:"charge_type"`
	ResourceRequest Resources `json:"resource_request"`
	Labels          string    `json:"labels"`
}

type CreateInstanceResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type TerminalSessionRequest struct {
	PodName       string `json:"pod_name"`
	ContainerName string `json:"container_name"`
	Shell         string `json:"shell"`
}

type TerminalSessionResponse struct {
	Code      int    `json:"code"`
	SessionId string `json:"session_id"`
	Message   string `json:"message"`
}

func (c *CreateInstanceRequest) Validate(req *CreateInstanceRequest) error {
	if req.Replicas < 1 {
		return fmt.Errorf("Validate Error: Replicas must be greater than zero")
	}
	return nil
}
