// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

import "fmt"

type (
	GPUResource struct {
		Type string
		Num  string
	}

	StorageResource struct {
		SystemDisk string
		DataVolume PVCResource
	}

	PVCResource struct {
		PVC  string
		Size string
	}

	Resources struct {
		CPU     string `json:"cpu"`
		Memory  string `json:"memory"`
		GPU     GPUResource
		GPUType string `json:"gpu_type"`
	}
)

type CreateInstanceRequest struct {
	RequestUUID     string
	CreateUser      string
	Name            string
	Replicas        int32
	Image           string
	ChargeType      string
	ResourceRequest Resources
	Labels          string
}

type CreateInstanceResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func (c *CreateInstanceRequest) Validate(req *CreateInstanceRequest) error {
	if req.Replicas < 1 {
		return fmt.Errorf("Validate Error: Replicas must be greater than zero")
	}
	return nil
}
