// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type CreateInstanceRequest struct {
	Uuid            string    `json:"uuid"`
	User            string    `json:"user,omitempty"`
	Name            string    `json:"name"`
	Image           string    `json:"image"`
	ChargeType      string    `json:"charge_type"`
	ResourceRequest Resources `json:"resource_request"`
	Labels          string    `json:"labels,omitempty"`
}

type (
	Resources struct {
		CPU     string          `json:"cpu"`
		Memory  string          `json:"memory"`
		Storage StorageResource `json:"storage"`
		GPU     GPUResource     `json:"gpu"`
	}
	StorageResource struct {
		SystemDisk string        `json:"system_disk"`
		DataVolume []PVCResource `json:"data_volume,omitempty"`
	}
	PVCResource struct {
		PVC  string `json:"pvc"`
		Size string `json:"size"`
	}
	GPUResource struct {
		Type string `json:"type"`
		Num  string `json:"num"`
	}
	Links struct {
		SSH_IP       string `json:"ssh_ip"`
		SSH_USER     string `json:"ssh_user"`
		SSH_Port     string `json:"ssh_port"`
		JUPYTER_PATH string `json:"jupyter_path"`
	}
)

type GetAllInstanceResponseData struct {
	ClusterName string     `json:"cluster_name"`
	Total       int        `json:"total"`
	Items       []Instance `json:"items"`
}

type GetInstanceRequest struct {
	Uuid string `json:"uuid"`
}

type GetInstanceResponseData struct {
	ClusterName string   `json:"cluster_name"`
	Item        Instance `json:"item"`
}

type Status string

const (
	StatusPreparing   Status = "Preparing"
	StatusCreating    Status = "Creating"
	StatusRunning     Status = "Running"     // 实例已暂停
	StatusTerminating Status = "Terminating" // 实例终止中
	StatusTerminated  Status = "Terminated"  // 实例已终止
	StatusFailed      Status = "Failed"      // 实例创建或运行失败
)

type Instance struct {
	Uuid            string    `json:"uuid"`
	Name            string    `json:"name"`
	User            string    `json:"user"`
	Status          Status    `json:"status"`
	Image           string    `json:"image"`
	CreateTime      string    `json:"create_time"`
	StartTime       string    `json:"start_time"`
	DeleteTime      string    `json:"delete_time"`
	ChargeType      string    `json:"charge_type"`
	Links           Links     `json:"links"`
	ResourceRequest Resources `json:"resource_request"`
}

type DeleteInstanceRequest struct {
	Uuid string `json:"uuid"`
}

type DeleteInstanceResponseData struct {
	Uuid string `json:"uuid"`
}

type Response struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    any    `json:"data,omitempty"`
}

type TerminalSessionRequest struct {
	Namespace     string `json:"namespace"`
	PodName       string `json:"pod_name"`
	ContainerName string `json:"container_name"`
	Shell         string `json:"shell"`
}

type TerminalSessionResponseData struct {
	SessionId string `json:"session_id"`
}

type NodeResourceInfo struct {
	Name        string `json:"name"`
	GPUType     string `json:"gpu-type"`
	Capacity    int    `json:"capacity"`
	Allocated   int    `json:"allocated"`
	Allocatable int    `json:"allocatable"`
}

type ClusterResourceResponseData struct {
	ClusterName string             `json:"cluster_name"`
	Nodes       []NodeResourceInfo `json:"nodes"`
}

func (r *CreateInstanceRequest) Validate(req *CreateInstanceRequest) error {
	return nil
}
