apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gpu-container-service.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gpu-container-service.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gpu-container-service.name" . }}
    namespace: {{ include "gpu-container-service.namespace" . }}