apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpu-container-service.name" . }}
  namespace: {{ include "gpu-container-service.namespace" . }}
  labels:
    {{- include "gpu-container-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gpu-container-service.selectorLabels" . | nindent 4 }}
